### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by anna-pokhilenko** [anna-pokhilenko/saas-website#2]
Hello) Hope your days are going well! 
I have a few questions,

1. I was working on my banner and its structure is a bit complicated. So my banner works well when my browser is in full screen but when it gets smaller my banner is a mess. I know I need to adjust it with mq but I won't be able to use typografier there because it is in CSS file. Do I guess the font sizes then? I wonder if there is an easy way to keep it nice and consistent. 
(I will attach the screenshot of my xD banner prototype so you could see what I am aiming at)
<img width="809" alt="Screen Shot 2020-04-16 at 3 19 05 PM" src="https://user-images.githubusercontent.com/55008926/79497450-b7778580-7ff5-11ea-8861-2bcced1b0bcc.png">

2. I also wanted to double-check when we use wrapper and when we use max-length. 

3. How do you apply opacity on the background colour?

Thank you!

@muxlowc
@HannahDelaney

**Comment by HannahDelaney** [comment]
1. @muxlowc may have a better suggestion about the use of consistent typografier classes with mqs. But I would suggest you can go into the `type.css` file and have a look at the sizing Thomas uses, and just apply those values to your own class names. You could try to override his class names but I find that doesn't usually work as well, and can be more confusing. If that doesn't help, let me know.

2. Wrapper and max-length classes have similar functions, for this particular case it is important to note that one will set the boundaries of your site wider than the other. They're kind of like setting margins. You'll want to have those classes on only the content that doesn't go right to the edges of your screen (ie. probably not background banner images). You'll need to account for that in your code set up, and have background images in a `div` layer or similar above the layer with those classes applied.

The cheatsheet has to say about those classes:
.wrapper
Sets the max-width of an element to 52em—which is a fairly good line-length for a website body.
There’s also .wrapper-no-center that doesn’t add the auto left & right margins.
.max-length
Sets the max-width of an element to 36em—which is a fairly good line-length for text content.
There’s also .max-length-no-center that doesn’t add the auto left & right margins.

3. You can use rgba values to set opacity. So when you set the colour instead of a hex code, write something like this: `rgba(0,0,0,0.5)`. This will give you a greyish colour, at 50% opacity. That is to say, r=0, g=0, b=0, and the opacity is 50%, or 0.5. Make sense?

**Comment by muxlowc** [comment]
@anna-pokhilenko  Thanks @HannahDelaney !

1) If you **really** want, you can create your tag line as an image and put and image flex on it (be sure to add an alt-tag so screen readers can read it). This is by far not the best solution but getting type to work exactly how you want it is a big headache, unfortunately haha. I would try using the image solution for now, and then come back to trying out positioning with absolute/relative again when you have time :) 
And yes, you can try overriding the typografier classes, like Hannah said, but also like she said that can get to be a bit confusing and may mess up your site should you use those same classes through your site.

**Comment by anna-pokhilenko** [comment]
Thank you! It makes more sense for me now.

I also have a problem with the images that I exported as png from xD and I couldn't find a way to make them centred and aligned...
<img width="1571" alt="Screen Shot 2020-04-16 at 4 25 44 PM" src="https://user-images.githubusercontent.com/55008926/79503427-23aab700-7fff-11ea-9a14-d93bda086192.png">
  

@muxlowc
@HannahDelaney

**Comment by muxlowc** [comment]
@anna-pokhilenko you might be able to try adding a class of center-content on that surrounding section that surrounds your img/h2/p

I would also change those smaller `<section>`s to be `<div>`s instead as they technically are parts of one section :)

**Comment by anna-pokhilenko** [comment]
I tried that but it didn't work, unfortunately. I might play with paddings and margins maybe... 
I also have the same problem with my button at the very bottom. 

And I guess I have created a trap for myself with my "It's All For You" section because I had to put some of my h3 after the p tags and when I am sizing it down those h3 end up below my p, of course. There is no way to fix it with mq, isn't it?...

And my wrapper doesn't work on that section when I size my page down to the mobile.

@muxlowc
@HannahDelaney

**Comment by muxlowc** [comment]
@anna-pokhilenko 


Try this:

```
<section class="wrapper">
        <h2 class="tera text-center center-content">Don’t Worry. <br> We Got Your Back</h2>
        
        <div class="grid grid-stretch">
          
          <div class="unit unit-content-distribute xs-1 s-1 m-1 l-1-3 text-center pad-t">
            <div class="center-content center content-fill">
              <img class="img-flex img-worry" src="images/tappy-disc.png" alt="">
              <h3 class="giga not-bold text-center push-1-2">Free Trial</h3>
              <p class="milli gutter text-center">No need to pay for our Tappy! Get it for free and enjoy our fast and easy-to-use model!</p>
            </div>
          </div>
```

**Comment by HannahDelaney** [comment]
For the wrapper thing:
Wrappers only add a max-width, so it is working. It doesn't create permanent space around the edges. You'll still need a gutter class or something to do that, the wrapper will just stop the content past a certain point.

**Comment by HannahDelaney** [comment]
Hmm. For the section that alternates. You might try looking into the flex feature of "ordering", which allows you to tell an item where to go. So you could have the content in the correct cascading order to maintain hierarchy, but you could tell the h3 to go after the p at certain sizes. I think that could maybe work? This would require using `display: flex` though.

Ordering is explained here, for quick access 😉 :
https://learn-the-web.algonquindesign.ca/topics/flexbox-cheat-sheet/

**Comment by anna-pokhilenko** [comment]
Hello) Thank you so much for your suggestions last time! It really saved me a lot of time and nerves :D
 
I fell like I am close to be done but still have some trouble with my banners. I tried different stuff but it all won't stay in place and right in the middle of the banner. I wonder if there is a way to just hammer it onto one place and let it just change the font sizes? haha

And for my tables, I want them to have a gutter between two but also couldn't find a way to make it work.

<img width="1091" alt="Screen Shot 2020-04-20 at 6 09 46 PM" src="https://user-images.githubusercontent.com/55008926/79804525-32140e00-8332-11ea-803a-d42567534bfc.png">

Thank you for all your hard work!

@muxlowc
@HannahDelaney

**Comment by muxlowc** [comment]
@anna-pokhilenko Hmm so I since you're using grids for your packages, adding any kind of padding/margins won't really work since they're taking up 100% of the width, so adding even an extra pixel will make them flex. This is where the gridifier settings can be slightly limiting as you would normally go in and maybe make these 48% rather than 50% so you can get a bit of a margin in there (so technically for this you can go into your gridifer and change your l-1-2 and m-1-2 to be 48% rather than 50%) or you can leave it as is. I'll leave it up to you :)

Have you tried putting the class of "pin-c" on your "slogan" and then adding the class of "relative" to your "img-large-screen" - this will pin your slogan image to the centre of the banner.

Or if you need something different between queries, you can add / play around with these in your main.css (the below is what pin-c gives, but you might need different percentages for different queries):

    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%);

**Comment by anna-pokhilenko** [comment]
@muxlowc

Good morning! (writing the message assuming that you will see it in the morning 😄)

I am attaching the screenshots of the quizzes that I've finished. 
I also feel like I am mostly done with everything (I will do some small final changes in design tomorrow), but Markbot still yells at me. I will fix as much as I can but I doubt that I will be able to pass it there anyways.

I also have done four pages instead of three:
1. **home**
2. **why tappy?**
3. **sign in**
4. **sign up**

<img width="702" alt="Screen Shot 2020-04-18 at 11 04 26 PM" src="https://user-images.githubusercontent.com/55008926/79942642-45f46880-8435-11ea-944c-a371bb2015f7.png">
<img width="678" alt="Screen Shot 2020-04-18 at 10 54 14 PM" src="https://user-images.githubusercontent.com/55008926/79942646-47be2c00-8435-11ea-85f8-d80dcd4aac3b.png">
<img width="758" alt="Screen Shot 2020-04-18 at 10 54 03 PM" src="https://user-images.githubusercontent.com/55008926/79942648-48ef5900-8435-11ea-80ee-1fe3f077375f.png">

**Comment by muxlowc** [comment]
@anna-pokhilenko no problem! due to the way the semester had to end, I will accept it no matter what Markbot has to say - just attach a screenshot of your markbot, and if you can rationalize why you chose to ignore some of markbot's suggestions, that's good enough for me :)

Thanks for the quizzes - I've marked them off!
